# Generated by Django 4.2 on 2023-04-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BuildingName", models.TextField(max_length=50)),
                ("RoomName", models.TextField(max_length=50)),
                ("BuildingNumber", models.TextField(max_length=50)),
                ("RoomNumber", models.TextField(max_length=50)),
                ("ManageDepartment", models.TextField(max_length=50)),
                ("ActualUse", models.TextField(max_length=50)),
                ("ClassroomCategorization", models.TextField(max_length=50)),
            ],
        ),
    ]
