# Generated by Django 4.1.7 on 2023-05-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="floor",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="building",
            name="floor_number",
            field=models.IntegerField(),
        ),
    ]
