# Generated by Django 4.1.7 on 2023-05-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0002_building_floor_alter_building_floor_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
