# Generated by Django 4.2 on 2023-04-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search",
            name="ActualUse",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="search",
            name="ClassroomCategorization",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="search",
            name="ManageDepartment",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AlterModelTable(
            name="search",
            table="baseinfo",
        ),
    ]
